# Generated by Django 3.1.1 on 2020-09-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200909_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='story',
            field=models.TextField(default='None'),
        ),
    ]
